rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Hero -> hero_hardware
      
      - rmcs_core::controller::gimbal::GimbalController -> gimbal_controller
      - rmcs_core::controller::pid::ErrorPidController -> yaw_angle_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> pitch_angle_pid_controller

      - rmcs_core::controller::chassis::ChassisController -> chassis_controller
      - rmcs_core::controller::chassis::OmniWheelController -> omni_wheel_controller

hero_hardware:
  ros__parameters:
    usb_pid_top_board: 0x652f
    usb_pid_bottom_board: 0xc1d3
    yaw_motor_zero_point: 27555
    pitch_motor_zero_point: 24514

gimbal_controller:
  ros__parameters:
    upper_limit: -0.4598
    lower_limit: 0.4362

yaw_angle_pid_controller:
  ros__parameters:
    measurement: /gimbal/yaw/control_angle_error
    control: /gimbal/yaw/control_velocity
    kp: 16.0
    ki: 0.0
    kd: 0.0

pitch_angle_pid_controller:
  ros__parameters:
    measurement: /gimbal/pitch/control_angle_error
    control: /gimbal/pitch/control_velocity
    kp: 16.00
    ki: 0.0
    kd: 0.0

bullet_feeder_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/bullet_feeder/velocity
    setpoint: /gimbal/bullet_feeder/control_velocity
    control: /gimbal/bullet_feeder/control_torque
    kp: 0.583
    ki: 0.0
    kd: 0.0

left_front_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/left_front_wheel/velocity
    setpoint: /chassis/left_front_wheel/control_velocity
    control: /chassis/left_front_wheel/control_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

left_back_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/left_back_wheel/velocity
    setpoint: /chassis/left_back_wheel/control_velocity
    control: /chassis/left_back_wheel/control_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

right_back_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/right_back_wheel/velocity
    setpoint: /chassis/right_back_wheel/control_velocity
    control: /chassis/right_back_wheel/control_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

right_front_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/right_front_wheel/velocity
    setpoint: /chassis/right_front_wheel/control_velocity
    control: /chassis/right_front_wheel/control_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00
