rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::cboard::Status -> cboard_status
      - rmcs_core::hardware::referee::Status -> referee_status

      - rmcs_core::controller::gimbal::GimbalController -> gimbal_controller
      - rmcs_core::controller::pid::ErrorPidController -> yaw_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> yaw_velocity_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> pitch_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> pitch_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> left_friction_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> right_friction_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> bullet_deliver_velocity_pid_controller

      - rmcs_core::controller::chassis::ChassisController -> chassis_controller
      - rmcs_core::controller::pid::PidController -> left_front_wheel_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> left_back_wheel_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> right_back_wheel_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> right_front_wheel_velocity_pid_controller
      - rmcs_core::controller::chassis::PowerController -> chassis_power_controller

      - rmcs_core::visualizer::TfVisualizer -> tf_visualizer

      - rmcs_core::hardware::cboard::Command -> cboard_command

      - ugas::Component -> ugas

cboard_status:
  ros__parameters:
    path: /dev/ttyACM0

referee_status:
  ros__parameters:
    path: /dev/ttyUSB0

yaw_angle_pid_controller:
  ros__parameters:
    measurement: /gimbal/yaw/control_angle_error
    control: /gimbal/yaw/control_velocity
    kp: 30.0
    ki: 0.1
    kd: 90.0
    integral_min: -0.5
    integral_max: 0.5

yaw_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/yaw/velocity_imu
    setpoint: /gimbal/yaw/control_velocity
    control: /gimbal/yaw/control_current
    kp: 5.2
    ki: 0.0
    kd: 0.0
    integral_min: -0.5
    integral_max: 0.5

pitch_angle_pid_controller:
  ros__parameters:
    measurement: /gimbal/pitch/control_angle_error
    control: /gimbal/pitch/control_velocity
    kp: 40.0
    ki: 0.1
    kd: 80.0
    integral_min: -1.5
    integral_max: 1.5

pitch_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/pitch/velocity_imu
    setpoint: /gimbal/pitch/control_velocity
    control: /gimbal/pitch/control_current
    kp: 3.8
    ki: 0.1
    kd: 0.0
    integral_min: -0.5
    integral_max: 0.5

left_friction_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/left_friction/velocity
    setpoint: /gimbal/left_friction/control_velocity
    control: /gimbal/left_friction/control_current
    kp: 0.22
    ki: 0.00
    kd: 0.6
    integral_min: -0.2
    integral_max: 0.2

right_friction_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/right_friction/velocity
    setpoint: /gimbal/right_friction/control_velocity
    control: /gimbal/right_friction/control_current
    kp: 0.22
    ki: 0.00
    kd: 0.6
    integral_min: -0.2
    integral_max: 0.2

bullet_deliver_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/bullet_deliver/velocity
    setpoint: /gimbal/bullet_deliver/control_velocity
    control: /gimbal/bullet_deliver/control_current
    kp: 0.09
    ki: 0.0
    kd: 0.0
    integral_min: -0.2
    integral_max: 0.2

left_front_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/left_front_wheel/velocity
    setpoint: /chassis/left_front_wheel/control_velocity
    control: /chassis/left_front_wheel/control_current_unrestricted
    kp: 0.07
    ki: 0.02
    kd: 0.01
    integral_min: -0.2
    integral_max: 0.2

left_back_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/left_back_wheel/velocity
    setpoint: /chassis/left_back_wheel/control_velocity
    control: /chassis/left_back_wheel/control_current_unrestricted
    kp: 0.07
    ki: 0.02
    kd: 0.01
    integral_min: -0.2
    integral_max: 0.2

right_back_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/right_back_wheel/velocity
    setpoint: /chassis/right_back_wheel/control_velocity
    control: /chassis/right_back_wheel/control_current_unrestricted
    kp: 0.07
    ki: 0.02
    kd: 0.01
    integral_min: -0.2
    integral_max: 0.2

right_front_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/right_front_wheel/velocity
    setpoint: /chassis/right_front_wheel/control_velocity
    control: /chassis/right_front_wheel/control_current_unrestricted
    kp: 0.07
    ki: 0.02
    kd: 0.01
    integral_min: -0.2
    integral_max: 0.2

chassis_power_controller:
  ros__parameters:
    motors:
      - /chassis/left_front_wheel
      - /chassis/left_back_wheel
      - /chassis/right_back_wheel
      - /chassis/right_front_wheel
