rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::forwarder::StateForwarder -> state_forwarder
      - rmcs_core::forwarder::CommandForwarder -> command_forwarder

state_forwarder:
  ros__parameters:
    path: /dev/ttyACM0

yaw_angle_pid:
  ros__parameters:
    p: 0.1
    i: 0.0
    d: 0.0