controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rmcs_controller:
      type: rmcs_controller/RMCS_Controller

rmcs_controller:
  ros__parameters:
    joints:
      - motor
    command_interfaces: ["effort"]
    state_interfaces: ["position", "velocity"]

    pid:
      kp: 20.0
      ki: 0.0
      kd: 50.0
