controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    rmcs_controller:
      type: rmcs_controller/RMCS_Controller

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rmcs_controller:
  ros__parameters:
    joints: ["motor"]
    state_joints: []
    interface_name: []
